[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gofundme = "DqFsjUeJduCUGx9PiGAdTgReRyU1oRfEX5jMctXcHCC8"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path tests/Cargo.toml -- --test-threads=1"

[hooks]
