[toolchain]
package_manager = "bun"

[features]
resolution = true
skip-lint = false

[programs.localnet]
gofundme = "9tgePyfBvvwE4LZbJ5t4TunpkQK6bLnTcT7T6ap1RJUr"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
